# Si possible à utiliser par la suite avec Spring boot pour remplacer 'application.properties'
# Le Yaml c'est plus lisible au niveau hiérarchique
# Pour le moment ceci est juste une représentation et ne sert à pas grand chose
dataSource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/vgarden
  username: postgres
  password: postgres
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hbm2ddl:
      auto: create
