spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/vgarden
    username: postgres
    password: postgres
logging:
  level:
    formation:
      sopra:
        vgarden: DEBUG
server:
  servlet:
    context-path: /api
